### ISSUE TITLE
Are we supposed to commit JARs

### ISSUE THREAD

**Issue by EricBoix** [smartgov-liris/SmartGovLezModel#13]
Note: my mileage is quite low in Java.

[JAR files](https://en.wikipedia.org/wiki/JAR_(file_format)) seem to be packages and (generally) are artifacts (as opposed to a manual process). Does [SmartGovLez-MASTER.jar](https://github.com/smartgov-liris/SmartGovLezModel/blob/master/SmartGovLez-MASTER.jar) belong to the git repository ?
Wouldn't it be more appropriate to document how to produce them (is this a gradlew task?) and delete that jar file from the repository ?

**Comment by elombardi2** [comment]
"Great minds think alike" :).
Removing the JAR file is in progress in [this PR](https://github.com/smartgov-liris/SmartGovLezModel/pull/12).

**Comment by vdeslandres** [comment]
What a nice label ;-)

**Comment by EricBoix** [comment]
Done in [this PR](https://github.com/smartgov-liris/SmartGovLezModel/pull/12).
Closing.
