### ISSUE TITLE
Plug the github pages for exposing the docs/ sub-directory

### ISSUE THREAD

**Issue by EricBoix** [smartgov-liris/SmartGovLezModel#3]
Refer to what is done in the SmartGovSimulator repository.

**Comment by vdeslandres** [comment]
I don't quite understand what I have to indicate: this repo is an instance of the simulator for the LEZ, do you want me to put a link to the SmartGovSimulator repo in the documentation?
Alban used an extended class of SmartGov (ExtendedSmartGov), I need to look where it is, if it is in SmartGovSimulator.

**Comment by vdeslandres** [comment]
GitHub Pages are activated, but the Docs pages don't appear yet... The issue has still to be fixed

**Comment by EricBoix** [comment]
Duplicate of [this issue](https://github.com/smartgov-liris/SmartGovSimulator/issues/10). Closing.
