### ISSUE TITLE
Fix documentation simulation descriptions

### ISSUE THREAD

**Issue by EricBoix** [smartgov-liris/SmartGovLezModel#6]
The docs concerning the simulation, as guessed from AFL report section 4.3:

[RG RUN](https://github.com/smartgov-liris/SmartGovLezModel/blob/master/documentation/README.md#result-generator-run)
 * Randomly generate policy configurations
 * For each such policy configuration realise the corresponding low-level simulation (i.e. the RUN stage) and store the result
 * The set of resulting  low-level simulation results are then used as input of a 
    neural network training (that is done with [SmartGovNN](https://github.com/smartgov-liris/SmartGovNN))

[P RUN](https://github.com/smartgov-liris/SmartGovLezModel/blob/master/documentation/README.md#politic-run)
 * objectif: find an optimal politic configuration
 * will use as input the result of the [SmartGovNN](https://github.com/smartgov-liris/SmartGovNN) predictor of low-level simulation result
 * how: uses a genetical algorithm (and NOT a reinforcement learning module) to find the optimum politic configuration thanks to the NN trained by SmartGovNN

The main process then goes:
 1. run RG RUN (separatly done at IN2p3 with ~80 000 low-level simulation done with the "RUN" stage)
 2. run SmartGovNN fed with the output of RG RUN
 3. run PRUN driven by the NN trained by SmartGovNN
![Main_Loop](https://user-images.githubusercontent.com/26405741/117116348-8992e980-ad8e-11eb-81fb-2f03a4950b20.png)

## Open question
Where is the trained NN (data file) resulting from the (external to this repository) SmartGovNN training ?

**Comment by elombardi2** [comment]
Tracing the execution of the command

`java -Xmx6g -jar $HOME/SmartGovLezModel/SmartGovLez-MASTER.jar prun -c ./input/static_config_lez.properties  -i 5`

inside the NNBest.java file reports that the following sections are run:
- https://github.com/smartgov-liris/SmartGovLezModel/blob/d62e8b548ea5a60e2d453b7aa18ea37df48daa76/src/main/java/org/liris/smartgov/lez/politic/policyagent/learning/strategy/NNBest.java#L66-L71
- https://github.com/smartgov-liris/SmartGovLezModel/blob/d62e8b548ea5a60e2d453b7aa18ea37df48daa76/src/main/java/org/liris/smartgov/lez/politic/policyagent/learning/strategy/NNBest.java#L82-L92
- https://github.com/smartgov-liris/SmartGovLezModel/blob/d62e8b548ea5a60e2d453b7aa18ea37df48daa76/src/main/java/org/liris/smartgov/lez/politic/policyagent/learning/strategy/NNBest.java#L144-L145

It seems that NO trained NN model is loaded. Only new (aka untrained) models are created. According to the console output, 16 models are created, which matches the 16 high-level policy agents (one by district). My conclusion is that the present code still implements the policy agents training based on Deep Reinforcement Learning as exposed in AFL report section 4.2.

The next question is: where is implemented the new approach exposed in AFL report section 4.3, where "real" simulations are replaced by simulation predictions (done by a pre-trained NN), and where the optimal policy is found with a genetical algorithm?

**Comment by vdeslandres** [comment]
@EricBoix I think that the NN model has been trained using IN2P3 machines, perhaps have a look at the in2p3-test branch?

**Comment by elombardi2** [comment]
I have checked the in2p3-test branch: there is nothing more on this branch than on master.

**Comment by elombardi2** [comment]
Some points were clarified by AFL.

1. The "Deep reinforcement learning" method described in section 4.2 of AFL report is  implemented in [SmartGovLezModel repository](https://github.com/smartgov-liris/SmartGovLezModel) ; this method is run by the [`prun` target of SmartGovLezModel executable](https://github.com/smartgov-liris/SmartGovLezModel/blob/master/documentation/README.md#politic-run). Note that the `rgrun` target of SmartGovLezModel is NOT related to this method (see below).

2. The "Deep learning plus genetic algorithm" method described in section 4.3 of AFL report is fully implemented in [SmartGovNN repository](https://github.com/smartgov-liris/SmartGovNN).

  Hints about using SmartGovNN:
  
  - the `config.txt` file contains the result of 86000 'real' simulations done with SmartGovLezModel ; this file could be re-generated by running the `rgrun` command of the SmartGovLezModel executable ([see SmartGovLezModel documentation](https://github.com/smartgov-liris/SmartGovLezModel/blob/master/documentation/README.md#result-generator-run))
  
  - use `python main.py -t config.txt` command to train the 'prediction-of-simulation-result NN' ; the output (aka the trained NN) is in the file `model.h5`
  
  - use `python main.py -u model.h5` command to run the genetic algorithm that will search for the optimal policy.

**Comment by EricBoix** [comment]
Place the pipeline diagram [here](https://github.com/smartgov-liris/SmartGovLezModel/blob/master/documentation/README.md#result-generator-run).

**Comment by elombardi2** [comment]
Done by [this PR](https://github.com/smartgov-liris/SmartGovLezModel/pull/11).
