### ISSUE TITLE
Init/run/tile steps of SmartGovLezModel produce inconsistent results

### ISSUE THREAD

**Issue by elombardi2** [smartgov-liris/SmartGovLezModel#9]
The SmartGovLezModelUFD model produces its results in 3 steps: *init*, *run*, *tile*. The final result is displayable with lez-viewer.

Running the same 3 steps with SmartGovLezModel leads to:
- the console output of the *init* and the *run* steps shows `0 agents added to SmartGovContext` whereas SmartGovLezModelUFD shows `100 agents added to SmartGovContext`,
- the final `tile_xxx.json` file weighs several hundreds of *MB* whereas the same file weighs hundreds of KB with SmartGovLezModelUFD,
- the final `tile_xxx.json` file is not displayed by lez-viewer,
- the final `tile_xxx.json` contains `"bounds":[[-1.7976931348623157E308,1.7976931348623157E308],[1.7976931348623157E308,-1.7976931348623157E308]]` whereas this file produced by SmartGovLezModelUFD contains `"bounds":[[46.1459999,4.4000008],[45.43,5.4599967]]` (which matches the OSM file extraction area).

So it seems that either the *init*, *run*, *tile* steps are bugged in SmartGovLezModel, or they are irrelevant with this model (but are mentioned in the documentation).

**Comment by EricBoix** [comment]
Decision: remove init, run and tile targets from the documentation.
Done in PR #10. Closed.
